name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
           docker buildx build --file Dockerfile --tag my-image-name:latest --tag my-image-name:$(git rev-parse --short $GITHUB_SHA) --push .

